spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    template:
      default-topic: library-inventory-dev
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
---
spring:
  profiles: prod
  kafka:
    bootstrap-servers: prod:9092,prod:9093,prod:9094
    template:
      default-topic: library-inventory-prod
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      bootstrap.servers: prod:9092,prod:9093,prod:9094